#!/usr/bin/env bash
set -e

echo "--- Generating dynamic boot.ipxe ---"
python3 compose.py

echo "--- Compiling iPXE with embedded script ---"
# Navigate to the source code (cloned in Dockerfile)
cd $SRC_DIR

# We build standard PCBIOS (bin/undionly.kpxe) and EFI (bin-x86_64-efi/ipxe.efi)
# EMBED points back to the file generated by your python script
make -j$(nproc) bin/undionly.kpxe bin-x86_64-efi/ipxe.efi EMBED=/work/boot.ipxe

echo "--- Exporting artifacts ---"
mkdir -p $OUTPUT_ROOT
cp bin/undionly.kpxe $OUTPUT_ROOT/
cp bin-x86_64-efi/ipxe.efi $OUTPUT_ROOT/

echo "Build complete. Artifacts are in $OUTPUT_ROOT"
