---
- name: Phase A - Hardware Provisioning (Local Execution)
  hosts: testXR11
  connection: local
  gather_facts: false

  vars:
      # Note: If you want the serial number, it is at: /redfish/v1/Chassis/System.Embedded.1, body: "SKU"
      # UNCOMMENT the line below to use a manual link instead of the API
      # generated_iso_url: "http://50.191.180.130/automation/custom-7d662a62ec8323c1/custom-7d662a62ec8323c1.iso"

  tasks:
    - name: Step 1 - Generate the ISO
      ansible.builtin.include_tasks: ./tasks/getCustomISO.yml
      when: generated_iso_url is not defined

    - name: Step 2 - Execute Redfish HW Sequence
      ansible.builtin.include_tasks: ./tasks/Dell/provisionDellHW.yml

# - name: Phase B - Post-Installation (SSH Execution)
#   hosts: testXR11
#   connection: ssh
#   become: true
#   # Note: Ansible will now use your SSH credentials from inventory
#   tasks:
#     - name: Update and Upgrade with Retry
#       ansible.builtin.apt:
#         update_cache: yes
#         upgrade: safe
#         # cache_valid_time: 3600  # Optional: Don't re-download if updated in last hour
#         dpkg_options: 'force-confold,force-confdef'
#       register: apt_result
#       until: apt_result is success
#       retries: 20            # Increased retries (cloud-init can sometimes take 5-10 mins)
#       delay: 30
#       environment:
#         DEBIAN_FRONTEND: noninteractive

